zarr_path: "/home/isihlangu/transient_sim/cube-1.zarr/"
source_type: "point_source"
varname: "cube"
stokes_par: "I"
start_index: 1500
duration: 8
integration: 2
positions: 
       - [2500, 2500]
       - [2500, 2500]
       - [2500, 2500]
       - [2500, 2500]
amplitude: [1.0, 1.0, 1.0, 1.0]
